---
data:
  mpii:
    raw: ../Datasets/MPIIFaceGaze
    obj: ../Datasets/mpii_3ddfa

  background_path: ../Datasets/val_256

supplementary:
  mpii: 
    source: supplementary/mpii/source_supply
    random_dark_ids: supplementary/mpii/random_dark_ids.txt
    random_lightings_ac: supplementary/mpii/random_lightings_ac.txt
    random_colors: supplementary/mpii/random_colors.txt
    random_bg_ids: supplementary/mpii/random_bg_ids.txt
    augmentation_ids: supplementary/mpii/augmentation_ids.txt

misc:
  mpii_face_model: supplementary/face_model.yml
  dlib_landmark_model: supplementary/shape_predictor_68_face_landmarks.dat
  openface_path: supplementary/OpenFace.txt

model:
  save_original_headpose: False
  ## mpii --> xgaze
  target_pose:
    number_new_views: 16
    mode: 'xgaze-train'
    headpose_file: ./targets/hp_train.npy

 
  ## mpii --> eyediap cs

  # target_pose:
  #   number_new_views: 16
  #   mode: 'eyediap-cs'
  #   headpose_file: ./targets/EYEDIAP_CS_head_distribution.txt

  ## mpii --> eyediap ft

  # target_pose:
  #   number_new_views: 16
  #   mode: 'eyediap-ft'
  #   headpose_file: ./targets/EYEDIAP_FT_head_distribution.txt


  ## mpii / xgaze --> gaussian
  
  # target_pose:
  #   number_new_views: 1
  #   mode: 'gaussian'
  #   sample_target_gaze: True
  #   sigma: 20
